name: play-fair
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cached-property=1.5.2
  - cudatoolkit=10.2.89
  - dash=1.17.0
  - dash-bootstrap-components=0.10.7
  - dash-core-components=1.13.0
  - dash-html-components=1.1.1
  - flask=1.1.2
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - gulpio=540.66
  - h5py=3.1.0
  - hdf5=1.10.6
  - ipdb=0.13.4
  - ipykernel=5.3.4
  - ipython=7.19.0
  - joblib=0.17.0
  - jsonnet=0.17.0
  - jpeg=9d
  - line_profiler=3.1.0
  - matplotlib-base=3.3.3
  - mkl=2020.4
  - numba=0.51.2
  - numpy=1.19.4
  - opencv=4.5.0
  - pandas=1.1.4
  - pillow=8.0.1
  - pingouin=0.3.8
  - pip=20.2.4
  - plotly=4.13.0
  - py-opencv=4.5.0
  - pydantic=1.7.2
  - pytest=6.1.2
  - python=3.7.8
  - pytorch=1.7.0
  - pyyaml=5.3.1
  - scikit-learn=0.23.2
  - scipy=1.5.3
  - seaborn=0.11.0
  - setuptools=50.3.1
  - sh=1.14.0
  - torchvision=0.8.1
  - tqdm=4.53.0
  - yaml=0.2.5
  - pip:
    - 'git+https://github.com/torchvideo/torchvideo.git#egg=torchvideo'
    - captum==0.3.0